import type { Product, StockChange } from '@/lib/types';

// This data is now only used for initial placeholder content 
// if the database is empty or for features not yet connected to Firebase.

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Minimalist Wooden Chair',
    sku: 'MWC-001',
    description: 'A modern, minimalist wooden chair, perfect for any contemporary living space.',
    category: 'Furniture',
    stock: 25,
    location: 'Warehouse A, Shelf 3',
    status: 'In Stock',
    threshold: 10,
    imageId: 'prod_001',
  },
  {
    id: 'prod_002',
    name: 'Sleek Ceramic Vase',
    sku: 'SCV-002',
    description: 'A sleek, black ceramic vase that adds a touch of elegance to your home decor.',
    category: 'Home Decor',
    stock: 8,
    location: 'Warehouse B, Shelf 1',
    status: 'Low Stock',
    threshold: 10,
    imageId: 'prod_002',
  },
  {
    id: 'prod_003',
    name: 'Geometric Cushions (Set of 3)',
    sku: 'GCS-003',
    description: 'A set of three decorative cushions with vibrant geometric patterns.',
    category: 'Textiles',
    stock: 40,
    location: 'Warehouse A, Shelf 2',
    status: 'In Stock',
    threshold: 15,
    imageId: 'prod_003',
  },
  {
    id: 'prod_004',
    name: 'Industrial Desk Lamp',
    sku: 'IDL-004',
    description: 'A large, industrial-style metal desk lamp with an adjustable arm.',
    category: 'Lighting',
    stock: 0,
    location: 'Warehouse C, Shelf 5',
    status: 'Out of Stock',
    threshold: 5,
    imageId: 'prod_004',
  },
  {
    id: 'prod_005',
    name: 'Abstract Wool Rug',
    sku: 'AWR-005',
    description: 'A hand-woven wool rug with a colorful abstract design to brighten up any room.',
    category: 'Rugs',
    stock: 12,
    location: 'Warehouse B, Shelf 4',
    status: 'In Stock',
    threshold: 5,
    imageId: 'prod_005',
  },
  {
    id: 'prod_006',
    name: 'Pro-Grade Knife Set',
    sku: 'PKS-006',
    description: 'A set of stainless steel kitchen knives on a magnetic block, for the aspiring chef.',
    category: 'Kitchenware',
    stock: 18,
    location: 'Warehouse C, Shelf 1',
    status: 'In Stock',
    threshold: 20,
    imageId: 'prod_006',
  },
  {
    id: 'prod_007',
    name: 'Glass & Gold Coffee Table',
    sku: 'GCT-007',
    description: 'An elegant glass coffee table with a sophisticated gold-finished metal frame.',
    category: 'Furniture',
    stock: 4,
    location: 'Showroom',
    status: 'Low Stock',
    threshold: 5,
    imageId: 'prod_007',
  },
  {
    id: 'prod_008',
    name: 'Chronos Smart Watch',
    sku: 'CSW-008',
    description: 'A feature-packed smart watch with a black silicone strap and a vibrant AMOLED display.',
    category: 'Electronics',
    stock: 55,
    location: 'Warehouse A, Shelf 1',
    status: 'In Stock',
    threshold: 25,
    imageId: 'prod_008',
  },
];

export const stockChanges: StockChange[] = [
  { productName: 'Minimalist Wooden Chair', productSku: 'MWC-001', change: -2, date: '2024-07-22' },
  { productName: 'Sleek Ceramic Vase', productSku: 'SCV-002', change: -5, date: '2024-07-22' },
  { productName: 'Chronos Smart Watch', productSku: 'CSW-008', change: -1, date: '2024-07-21' },
  { productName: 'Pro-Grade Knife Set', productSku: 'PKS-006', change: 10, date: '2024-07-20' },
  { productName: 'Abstract Wool Rug', productSku: 'AWR-005', change: -1, date: '2024-07-20' },
];
